#include "mylibnet.h"
#include "mac.h"
#include "ip.h"
#include "ethhdr.h"
#include "arphdr.h"
#include <string>
#include <stdint.h>
#include <ifaddrs.h>
#include <sys/socket.h>
#include <iostream>
#include <vector>
#include <algorithm>
#include <fstream>
#include <map>
#include <cstdio>
#include <pcap.h>
#include <pthread.h>